
#PostgreSql
spring.application.name=transportfirm
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-square-cloud-amx11bui.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_SAiG71OKmvYH}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional but helpful
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


jwt.secret.key=${JWT_SECRET:}
server.servlet.context-path=/api

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:transtrackbg@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hzeflcjjnmmzzhja}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio SMS
twilio.account-sid=${TWILIO_ACCOUNT_SID:ACe7f5848aa1d938d91d8a8f67347336e7}
twilio.auth-token=${TWILIO_AUTH_TOKEN:64ba841cfd6d93858a152b8f0f06c0c5}
twilio.from-number=${TWILIO_FROM_NUMBER:+1 814 277 3360}
twilio.enabled=${SMS_ENABLED:true}
